### ISSUE TITLE
AmbisonicShelfFilters.cpp missing from CMakeLists.txt?

### ISSUE THREAD

**Issue by Warblefly** [videolabs/libspatialaudio#21]
Hello,

On compiling the new GitHub version, some unresolved symbols in the shared library appeared on linking. This is on the Mingw-w64 platform, cross-compiling from Linux.

I needed to add source/AmbisonicShelfFilters.cpp to the CMakeLists.txt sources list to get it to compile.

with best wishes
JW

**Comment by jbkempf** [comment]
True. See #22
